language: python
python:
- '3.6'
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database momo_bank;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- coverage run --source="." manage.py test
- coverage report -m
after_script:
- coverage xml
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
