# Generated by Django 3.0 on 2020-01-03 07:55

from django.db import migrations


def create_default_bank(apps, schema_editor):
    Bank = apps.get_model('bank', 'Bank')
    bank = Bank()
    bank.name = 'Momo Bank'
    bank.district = 'Kampala'
    bank.country = 'Uganda'
    bank.tin = 'tinNo'
    bank.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_bank),
    ]
